/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Controlador.Controlador_FRM_MantenimientoCursos;

/**
 *
 * @author Keren
 */
public class FRM_MantenimientoCursos extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoCursos
     */
    
    Controlador_FRM_MantenimientoCursos controlador_FRM_MantenimientoCursos;
   
    
    public FRM_MantenimientoCursos() {
        initComponents();
        setVisible(false);
        
        controlador_FRM_MantenimientoCursos= new Controlador_FRM_MantenimientoCursos(this);
        gUI_Botones2.agregarEventos(controlador_FRM_MantenimientoCursos);
    }
    public String[] devolverInformacion()
    {
        return this.gUI_InformacionCursos2.devolverInformacion();
    }
    public String devolverCedula()
    {
        return this.gUI_InformacionCursos2.devolverNombreCurso();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.gUI_InformacionCursos2.mostrarInformacion(arreglo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gUI_InformacionCursos2 = new Vista.GUI_InformacionCursos();
        gUI_Botones2 = new Vista.GUI_Botones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(gUI_InformacionCursos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(gUI_Botones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gUI_InformacionCursos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gUI_Botones2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String devolverNombreCurso() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.GUI_Botones gUI_Botones2;
    private Vista.GUI_InformacionCursos gUI_InformacionCursos2;
    // End of variables declaration//GEN-END:variables
}
