/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

/**
 *
 * @author Keren
 */
public class GUI_InformacionCursos extends javax.swing.JPanel {

    /**
     * Creates new form GUI_InformacionCursos
     */
    public GUI_InformacionCursos() {
        initComponents();
    }
    
    public String[] devolverInformacion() 
    {
        String arreglo[];
        arreglo=new String [3];
        arreglo[0]=this.jt_NombreCurso.getText();
        arreglo[1]=this.jt_SiglasCurso.getText();
        arreglo[2]=this.jt_Creditos.getText();
        
        return arreglo;
    }
    public String devolverNombreCurso()
    {
        return this.jt_NombreCurso.getText();
    }
    public void mostrarInformacion(String arreglo[])
    {
        this.jt_SiglasCurso.setText(arreglo[0]);
        this.jt_Creditos.setText(arreglo[1]);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_NombreCurso = new javax.swing.JLabel();
        jl_SiglasCurso = new javax.swing.JLabel();
        jl_Creditos = new javax.swing.JLabel();
        jt_NombreCurso = new javax.swing.JTextField();
        jt_SiglasCurso = new javax.swing.JTextField();
        jt_Creditos = new javax.swing.JTextField();
        btn_consultaRapida = new javax.swing.JButton();

        jl_NombreCurso.setText("Nombre del curso");

        jl_SiglasCurso.setText("Siglas del curso");

        jl_Creditos.setText("Créditos");

        jt_SiglasCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_SiglasCursoActionPerformed(evt);
            }
        });

        jt_Creditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt_CreditosActionPerformed(evt);
            }
        });

        btn_consultaRapida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_Creditos)
                        .addGap(53, 53, 53)
                        .addComponent(jt_Creditos))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jl_SiglasCurso)
                        .addGap(20, 20, 20)
                        .addComponent(jt_SiglasCurso))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_NombreCurso)
                        .addGap(10, 10, 10)
                        .addComponent(jt_NombreCurso, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_consultaRapida)))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jt_NombreCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jl_NombreCurso))
                    .addComponent(btn_consultaRapida))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_SiglasCurso)
                    .addComponent(jt_SiglasCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Creditos)
                    .addComponent(jt_Creditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jt_CreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_CreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_CreditosActionPerformed

    private void jt_SiglasCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt_SiglasCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jt_SiglasCursoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultaRapida;
    private javax.swing.JLabel jl_Creditos;
    private javax.swing.JLabel jl_NombreCurso;
    private javax.swing.JLabel jl_SiglasCurso;
    private javax.swing.JTextField jt_Creditos;
    private javax.swing.JTextField jt_NombreCurso;
    private javax.swing.JTextField jt_SiglasCurso;
    // End of variables declaration//GEN-END:variables
}
